# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2025-01-24 14:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='editor',
            options={'ordering': ['nombre']},
        ),
    ]
